branches:
  only:
    - "master"
language: python
python:
    - "3.8"
    - "3.9"
# Command to install dependencies
install:
    - pip install -r requirements_dev.txt
# command to run tests
script:
    - pytest tests -v --cov
