[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "monolg"
version = "0.0.1"
description="Centralized logging for Python using MongoDB"
readme = "README.md"
authors = [{ name = "Pranesh Mukhopadhyay", email = "praneshmukherjee7@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["logging", "mongodb", "monolg"]
dependencies = {file = ["requirements.txt"]}
