# https://github.com/psf/black
[tool.black]
target-version = ["py39"]
color = false
line-length = 120

exclude = '''
/(
    \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | build
    | venv
)/
'''

[tool.mypy]
mypy_path = "monolg"
# check_untyped_defs = true
# disallow_any_generics = true
# ignore_missing_imports = true
# no_implicit_optional = true
# show_error_codes = true
# strict_equality = true
# warn_redundant_casts = true
# warn_return_any = true
# warn_unreachable = true
# warn_unused_configs = true
# no_implicit_reexport = true